### ISSUE TITLE
estimate_parameters error

### ISSUE THREAD

**Issue by anashen** [statdivlab/tinyvamp#6]
Hello,

I am a part of the Karstens Lab and I am excited to use the `tinyvamp` package! I am currently working through the `dilution_series` vignette to understand how to apply the package. I ran into some issues with the `estimate_parameters` function.

I ran the code block with the following code:
```
full_karstens_model <- estimate_parameters(W = W,
                                           X = X,
                                           Z = Z,
                                           Z_tilde = Z_tilde,
                                           Z_tilde_gamma_cols = Z_tilde_gamma_cols,
                                           gammas = gammas,
                                           gammas_fixed_indices = gammas_fixed_indices,
                                           P = P,
                                           P_fixed_indices = P_fixed_indices,
                                           B = B,
                                           B_fixed_indices = B_fixed_indices,
                                           X_tilde = X_tilde,
                                           P_tilde = P_tilde,
                                           P_tilde_fixed_indices = P_tilde_fixed_indices,
                                           gamma_tilde = gamma_tilde,
                                           gamma_tilde_fixed_indices = gamma_tilde_fixed_indices,
                                           criterion = "reweighted_Poisson")
```
Here is the error I received: `Error in estimate_parameters(W = W, X = X, Z = Z, Z_tilde = Z_tilde, Z_tilde_gamma_cols = Z_tilde_gamma_cols,  : object 'prop_lr_df' not found`

In troubleshooting, I was able to trace the origin of the `prop_lr_df` object and noticed it required the `ra_to_lr` and `parameters_to_dataframes` functions, which I then included in the program before re-running. 

This did not resolve the error; would you be able to point me in the right direction to find the root of the issue?

Thanks so much!

**Comment by adw96** [comment]
Hi @anashen , and thanks for using `tinyvamp`! 

I've tried a few things and I can't reproduce the error you describe. However, I've run into this issue myself before but I thought we fixed it in a more recent commit. Can you run the following code for me and tell me if it errors for you?

```
library(tidyverse)
library(speedyseq)
remotes::install_github("statdivlab/tinyvamp")
library(tinyvamp)
data("karstens_phyloseq")
karstens_phyloseq
genera_data <- karstens_phyloseq %>% tax_table %>% as_tibble %>% select("Genus") %>% pull
Pseudomonas <- genera_data %>% str_detect("Pseudomonas") %>% which
Escherichia <- genera_data %>% str_detect("Escherichia") %>% which
Salmonella <- genera_data %>% str_detect("Salmonella") %>% which
Limosilactobacillus <- genera_data %>% str_detect("Limosilactobacillus") %>% which
Enterococcus <- genera_data %>% str_detect("Enterococcus") %>% which
Staphylococcus <- genera_data %>% str_detect("Staphylococcus") %>% which
Listeria <- genera_data %>% str_detect("Listeria") %>% which
Bacillus <- genera_data %>% str_detect("Bacillus") %>% which
mock_taxa <- c(Pseudomonas,
               Escherichia,
               Salmonella[1],
               Enterococcus,
               Staphylococcus,
               Listeria,
               Bacillus,
               Limosilactobacillus)
W <- karstens_phyloseq %>% otu_table %>% as.matrix
jj <- ncol(W)
W <- cbind(W[ , !(1:jj %in% mock_taxa)],
           W[ , mock_taxa])
W <- W[order(rownames(W)), ]
Z <- matrix(1, ncol = 1, nrow = 9)
P <- matrix(c(rep(0, 240), rep(1/8, 8)), nrow = 1, ncol = jj)
P_fixed_indices <- matrix(TRUE, nrow = 1, ncol = jj)

B_fixed_indices <- matrix(TRUE, ncol = jj, nrow = 1)
B_fixed_indices[1, 241:247] <- FALSE
B <- matrix(0, ncol = jj, nrow = 1)
X <- matrix(1, nrow = nrow(W), ncol = 1)

gammas_fixed_indices <- rep(FALSE, nrow(W))
gammas <- log(apply(W, 1, sum)) + rnorm(nrow(W))
Z_tilde <- matrix(3^(0:8)/exp(mean(log(3^(0:8)))), ncol = 1)
Z_tilde_gamma_cols <- 1 

gamma_tilde <- matrix(0, nrow = 1, ncol = 1)
gamma_tilde_fixed_indices <- matrix(FALSE, nrow = 1, ncol = 1)

P_tilde <- matrix(c(rep(1/(jj - 1), jj - 1), 0), ncol = jj, nrow = 1)
P_tilde_fixed_indices <- matrix(c(rep(FALSE, jj - 1), TRUE), ncol = jj, nrow = 1)
X_tilde <- matrix(0, nrow = 1, ncol = 1) 

full_karstens_model <- estimate_parameters(W = W,
                                           X = X,
                                           Z = Z,
                                           Z_tilde = Z_tilde,
                                           Z_tilde_gamma_cols = Z_tilde_gamma_cols,
                                           gammas = gammas,
                                           gammas_fixed_indices = gammas_fixed_indices,
                                           P = P,
                                           P_fixed_indices = P_fixed_indices,
                                           B = B,
                                           B_fixed_indices = B_fixed_indices,
                                           X_tilde = X_tilde,
                                           P_tilde = P_tilde,
                                           P_tilde_fixed_indices = P_tilde_fixed_indices,
                                           gamma_tilde = gamma_tilde,
                                           gamma_tilde_fixed_indices = gamma_tilde_fixed_indices,
                                           criterion = "reweighted_Poisson")
```

If so, can you share the output of `sessionInfo()`?

**Comment by anashen** [comment]
Thank you for your quick response @adw96! 

Unfortunately, the error persists. Here is the output of `sessionInfo()`:
```
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] speedyseq_0.5.3.9018 phyloseq_1.40.0      tinyvamp_0.0.2.0     numDeriv_2016.8-1.1 
 [5] logsum_0.1.0         fastnnls_0.0.0.9000  cir_2.2.0            forcats_0.5.1       
 [9] stringr_1.4.0        dplyr_1.0.9          purrr_0.3.4          readr_2.1.2         
[13] tidyr_1.2.0          tibble_3.1.7         ggplot2_3.3.6        tidyverse_1.3.1     

loaded via a namespace (and not attached):
 [1] nlme_3.1-158           bitops_1.0-7           fs_1.5.2               lubridate_1.8.0       
 [5] httr_1.4.3             GenomeInfoDb_1.32.2    tools_4.2.0            backports_1.4.1       
 [9] vegan_2.6-2            utf8_1.2.2             R6_2.5.1               mgcv_1.8-40           
[13] DBI_1.1.3              BiocGenerics_0.42.0    colorspace_2.0-3       permute_0.9-7         
[17] rhdf5filters_1.8.0     ade4_1.7-19            withr_2.5.0            tidyselect_1.1.2      
[21] curl_4.3.2             compiler_4.2.0         cli_3.3.0              rvest_1.0.2           
[25] Biobase_2.56.0         xml2_1.3.3             scales_1.2.0           digest_0.6.29         
[29] rmarkdown_2.14         XVector_0.36.0         pkgconfig_2.0.3        htmltools_0.5.2       
[33] dbplyr_2.2.1           fastmap_1.1.0          rlang_1.0.3            readxl_1.4.0          
[37] rstudioapi_0.13        generics_0.1.2         jsonlite_1.8.0         RCurl_1.98-1.7        
[41] magrittr_2.0.3         GenomeInfoDbData_1.2.8 Matrix_1.4-1           biomformat_1.24.0     
[45] Rhdf5lib_1.18.2        Rcpp_1.0.8.3           munsell_0.5.0          S4Vectors_0.34.0      
[49] fansi_1.0.3            ape_5.6-2              lifecycle_1.0.1        stringi_1.7.6         
[53] yaml_2.3.5             MASS_7.3-57            zlibbioc_1.42.0        rhdf5_2.40.0          
[57] plyr_1.8.7             grid_4.2.0             crayon_1.5.1           lattice_0.20-45       
[61] splines_4.2.0          Biostrings_2.64.0      haven_2.5.0            multtest_2.52.0       
[65] hms_1.1.1              knitr_1.39             pillar_1.7.0           igraph_1.3.2          
[69] reshape2_1.4.4         codetools_0.2-18       stats4_4.2.0           reprex_2.0.1          
[73] glue_1.6.2             evaluate_0.15          data.table_1.14.2      remotes_2.4.2         
[77] modelr_0.1.8           vctrs_0.4.1            tzdb_0.3.0             foreach_1.5.2         
[81] cellranger_1.1.0       gtable_0.3.0           assertthat_0.2.1       xfun_0.31             
[85] broom_0.8.0            survival_3.3-1         iterators_1.0.14       IRanges_2.30.0        
[89] cluster_2.1.3          ellipsis_0.3.2
```
Please let me know if there is any other information I can provide. Thank you so much for your help!

**Comment by adw96** [comment]
I'm really sorry, @anashen, but I and a couple of lab members have tried and we can't seem to reproduce your error. 

Can I confirm that you've tried this in a new R Project, in its own folder, with nothing else loaded? And also that the `remotes::install_github("statdivlab/tinyvamp")` is indeed downloading the latest version?

I'm sorry for the trouble. Short of hopping on a call, I'm not sure how to help. Let me know how you want to proceed.

**Comment by anashen** [comment]
@adw96, I really appreciate your time and effort in helping me with this error. I ran the code successfully after updating the `tinyvamp` package in a new R session. 

As a side note, I ran the install command `remotes::install_github("statdivlab/tinyvamp")` earlier today to update the package after facing the issue (and this command was also in the code you asked I run). At that time, the error persisted even after running the install command. I am not sure what differences in sessions led to the difference in outcome, but I am glad that updating the package has resolved the error.

Thank you so much for all your help!
